server:
  port: 9000

spring:
  application:
    name: shiro-rbac-admin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_rbac?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root312

    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQL异常
      minimum-idle: 10 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000 # 连接超时时间，单位：毫秒
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true



jwt:
  secretKey: ertepejrwejkwswg24bgvrd # token密钥
  expiration: 604800 # token到期时间，单位：秒
